#!/usr/bin/env bash
set -e

# Overwrite a few variables, this allows us to use the same template
# for both development, staging and production.
CONFIG_PATH="/etc/nginx/conf.d/default.conf"
STAGING_IP="104.131.134.242"
STAGING_HOSTNAME="lyfeshoppe"
DOMAIN_NAME="lyfeshoppe.com"

if [[ $(hostname) != "${STAGING_HOSTNAME}" ]]; then
  sed -i "s/${STAGING_IP}/${DOMAIN_NAME}/g" "${CONFIG_PATH}"
fi

# Execute the CMD from the Dockerfile.
exec "$@"
